services:
  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER


  schemas_loader:
    build:
      context: ./schemas_loader
      dockerfile: Dockerfile
    container_name: schemas_loader
    env_file:
      - ./.env
    depends_on: 
      - schema-registry
  

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
    depends_on:
      - kafka


  auth_service_db:
    image: postgres:14
    container_name: auth_service_db
    environment:
      - POSTGRES_USER=auth_service
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=db
    restart: unless-stopped


  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    env_file:
      - ./auth_service/.env
      - ./.env
    ports:
      - 8000:8001
    depends_on:
      - auth_service_db
      - kafka


  paste_service_db:
    image: postgres:14
    container_name: paste_service_db
    environment:
      - POSTGRES_USER=paste_service
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=db
    restart: unless-stopped
  
  
  paste_service:
    build:
      context: ./paste_service
      dockerfile: Dockerfile
    container_name: paste_service
    env_file:
      - ./paste_service/.env
      - ./.env
    ports:
      - 9000:8002
    depends_on:
      - paste_service_db
      - kafka
    restart: unless-stopped